# Generated by Django 4.2.11 on 2025-01-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_posproduct_postransaction_postransactionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
