# Generated by Django 4.2.11 on 2025-01-29 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0037_postransaction_collected_postransaction_collected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posproduct',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postransaction',
            name='order_number',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='postransaction',
            unique_together={('order_number', 'user')},
        ),
    ]
