# Generated by Django 4.2.11 on 2025-02-18 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0038_posproduct_user_postransaction_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_for', models.CharField(max_length=20)),
                ('user_explanation', models.TextField(blank=True)),
                ('predicted_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predicted_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('growth_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confidence_level', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='core.salesforecast')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='core.salesforecast')),
            ],
        ),
    ]
