# Generated by Django 4.2.11 on 2025-02-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_salesforecast_forecasttip_forecastfactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecasttip',
            name='forecast',
        ),
        migrations.AlterModelOptions(
            name='salesforecast',
            options={},
        ),
        migrations.RenameField(
            model_name='salesforecast',
            old_name='created_at',
            new_name='forecast_date',
        ),
        migrations.RemoveField(
            model_name='salesforecast',
            name='confidence_level',
        ),
        migrations.RemoveField(
            model_name='salesforecast',
            name='forecast_for',
        ),
        migrations.RemoveField(
            model_name='salesforecast',
            name='growth_rate',
        ),
        migrations.RemoveField(
            model_name='salesforecast',
            name='predicted_profit',
        ),
        migrations.RemoveField(
            model_name='salesforecast',
            name='predicted_sales',
        ),
        migrations.RemoveField(
            model_name='salesforecast',
            name='user_explanation',
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='forecast_data',
            field=models.TextField(default='nothing'),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='situational_factors',
            field=models.TextField(default='nothing'),
        ),
        migrations.DeleteModel(
            name='ForecastFactor',
        ),
        migrations.DeleteModel(
            name='ForecastTip',
        ),
    ]
