# Generated by Django 4.2.11 on 2025-03-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_forecasttip_forecast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='barcode',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
