# Generated by Django 4.2.11 on 2025-04-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_barcode_price_barcode_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postransactionitem',
            old_name='price',
            new_name='product_price',
        ),
        migrations.RemoveField(
            model_name='postransactionitem',
            name='product',
        ),
        migrations.AddField(
            model_name='postransactionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='postransactionitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postransactionitem',
            name='product_type',
            field=models.CharField(blank=True, choices=[('main', 'Main Inventory'), ('pos', 'POS Product')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postransactionitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
