# Generated by Django 4.2.11 on 2025-04-03 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_rename_price_postransactionitem_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postransactionitem',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='postransactionitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='postransactionitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='postransactionitem',
            name='product_type',
        ),
        migrations.AddField(
            model_name='postransactionitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.posproduct'),
        ),
        migrations.AlterField(
            model_name='postransactionitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
