# Generated by Django 4.2.11 on 2025-04-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_rename_product_price_postransactionitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransactionitem',
            name='inventory_product_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postransactionitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
