# Generated by Django 4.2.11 on 2025-04-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_postransactionitem_inventory_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postransactionitem',
            name='inventory_product_id',
        ),
        migrations.RemoveField(
            model_name='postransactionitem',
            name='product_name',
        ),
    ]
