# Generated by Django 4.2.11 on 2025-04-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_postransactionitem_inventory_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransactionitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
