# Generated by Django 4.2.17 on 2025-08-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_postransactionitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
