# Generated by Django 4.2.17 on 2025-08-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_stockimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
