# Generated by Django 5.2.7 on 2025-10-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_category_name'),
        ('core', '0050_alter_category_name_and_more'),
    ]

    operations = [
    ]
