# Generated by Django 5.2.7 on 2025-10-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_merge_20251020_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='profit_loss_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
