# Generated by Django 5.2.7 on 2025-10-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_product_profit_loss_product_profit_loss_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
