# Generated by Django 5.2.5 on 2025-09-04 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='styleticket',
            old_name='service',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='styleticket',
            old_name='employee',
            new_name='worker',
        ),
        migrations.RemoveField(
            model_name='style',
            name='user',
        ),
        migrations.RemoveField(
            model_name='styleticket',
            name='car_number_plate',
        ),
        migrations.RemoveField(
            model_name='styleticket',
            name='user',
        ),
        migrations.AddField(
            model_name='style',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='styleticket',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='styleticket',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_tickets_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='styleticket',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='styleticket',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
