# Generated by Django 5.2.5 on 2025-09-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0002_rename_service_styleticket_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='is_active',
        ),
    ]
