# Generated by Django 5.2.7 on 2025-10-15 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignimage',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='email_campaigns.emailcampaign'),
        ),
    ]
