# Generated by Django 5.2.7 on 2025-10-15 19:29

import core.project.gcloud
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaigns', '0002_alter_campaignimage_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignimage',
            name='image',
            field=models.ImageField(storage=core.project.gcloud.GoogleCloudMediaFileStorage(), upload_to='campaign_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
