# Generated by Django 4.2.11 on 2024-12-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0038_paymenthistory_remove_subscription_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='paystack_plan_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='tTx7afTqEA597hxpc6jbNzrf2M1VKHpm', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='xMpxTi10qENnzeTToteFthgSvHVO1VJi', editable=False, max_length=32, unique=True),
        ),
    ]
