# Generated by Django 4.2.11 on 2024-12-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0039_subscriptionplan_paystack_plan_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='kY9p79ILbGkvQhT78ocuGTcFpBgdjyvm', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Ml8yuzgxHussbUWjqUBLwJ6wSbcSsZDQ', editable=False, max_length=32, unique=True),
        ),
    ]
