# Generated by Django 4.2.11 on 2024-12-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0040_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='eHTEMSo5IlGMv1gkU0JcOVHCKp2H8shf', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.customuser'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='a19YwO28AIi5QDXFxGK4ZG3KJZG5FfB2', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='submit.customuser'),
        ),
    ]
