# Generated by Django 4.2.11 on 2024-12-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0041_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='product_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='fXidTi6ft7VMzAkNJQaQSBPdmYdPHErK', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='yfAx4vbCEoAY5FBvYZI7aN6ioDIP13r1', editable=False, max_length=32, unique=True),
        ),
    ]
