# Generated by Django 4.2.11 on 2024-12-26 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0042_subscriptionplan_product_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='KwRfAiHuUUkM5pnQT8MPn7VtfXqhJH4u', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='rpHogIdQpaSS8gj3z4pyvSBQdMBo275b', editable=False, max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='ProductPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('product_count', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.profile')),
            ],
        ),
    ]
