# Generated by Django 4.2.11 on 2024-12-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0043_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='8gSTFtVHhkHfGaEnKqazeag4ifkwOGpJ', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='1ldzrAdlexDoSEtNgsw0DH5sZOGtUdad', editable=False, max_length=32, unique=True),
        ),
    ]
