# Generated by Django 4.2.11 on 2024-12-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0044_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='KjMUnnob0xgek5WCttD6kA0PzRWeKdtP', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Rvf6juOeyEGGh2NRqC569iezjeFeeRMP', editable=False, max_length=32, unique=True),
        ),
    ]
