# Generated by Django 4.2.11 on 2024-12-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0045_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='YwSqcyCgFlgUrWeWa9yeRPOLaZwkPCNx', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='sKhJYQC8rIIMtlmAN5Le5dbIkYXffSgP', editable=False, max_length=32, unique=True),
        ),
    ]
