# Generated by Django 4.2.11 on 2024-12-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0046_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='ba6AE5KmUpCHVJ5bUE58yJRNWQho2GKd', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ZwMSh70niG6v0SLTOlMYTyrpnGZyW1zQ', editable=False, max_length=32, unique=True),
        ),
    ]
