# Generated by Django 4.2.11 on 2024-12-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0047_remove_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='QAuZsXIrBqXlCBFLOUbGCp2GCCkPGfmg', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='VcUn2h3dadY8Ifz8iG39RkOVLc9xyU3b', editable=False, max_length=32, unique=True),
        ),
    ]
