# Generated by Django 4.2.11 on 2024-12-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0048_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='e4PRpTw42v6BYqAM4DrYMEncMBrg96MJ', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='9xjzdLdRR1U1marvkFKLaF5XwmOMP5Qv', editable=False, max_length=32, unique=True),
        ),
    ]
