# Generated by Django 4.2.11 on 2024-12-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0049_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='oQpSlmstAGS1y4GvPfznXpxzmjI6g0NF', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='AHKBzVmS24lG8Smh798yqOEZeYl7R0AN', editable=False, max_length=32, unique=True),
        ),
    ]
