# Generated by Django 4.2.11 on 2025-01-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0050_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='hui8Vpko33QF5vcqEPZ2blKlkaXKJI7B', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='RsTw6SvNcG0B4knImyVGbh6imQWv3mlp', editable=False, max_length=32, unique=True),
        ),
    ]
