# Generated by Django 4.2.11 on 2025-01-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0051_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='bLM3K2QIQiPYrO1Siq6aGUfwteWwp33k', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='zIRGPw6BCiXJRDTCyzOYpqqc1Ku9XuAp', editable=False, max_length=32, unique=True),
        ),
    ]
