# Generated by Django 4.2.11 on 2025-01-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0052_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='T7IKowPuVmDBxSHL7DqaL9W1GyIRjhbI', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='iQgng68tqKbuCm5azRSm3L8dd1MIsDA0', editable=False, max_length=32, unique=True),
        ),
    ]
