# Generated by Django 4.2.11 on 2025-02-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0053_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='52aOKM79xk4UMlLvJQGXNm7fL6IKEBAb', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='gR8LAImynTjQujajeDSWFu0JKf8jbAGO', editable=False, max_length=32, unique=True),
        ),
    ]
