# Generated by Django 4.2.11 on 2025-02-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0054_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='6usYjAAbjRiKudbWXccHMHo9Tg7rhEVk', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='XO1LmbFl3iTW6ljOItf6L90zdPATrHu1', editable=False, max_length=32, unique=True),
        ),
    ]
