# Generated by Django 4.2.11 on 2025-03-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0055_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_category',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('clothing_brand', 'Clothing Brand'), ('market', 'Market')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='SHcjvsaXD7TLzkEoZMCiW1KXSg1opBhH', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='6IUo1rmaT6Blt6EBiEgSoLXAA7dtPYzh', editable=False, max_length=32, unique=True),
        ),
    ]
