# Generated by Django 4.2.11 on 2025-03-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0056_customuser_company_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='kzpu6HPebwD3RJZm3Ivn2wfQqLry8QkT', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='QBM1Pucat6ORYJmyZh6KrdMgemYIOC0w', editable=False, max_length=32, unique=True),
        ),
    ]
