# Generated by Django 4.2.11 on 2025-03-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0057_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='nNMaPA6wCaVzPuYmxMTYs07WwyDCscsH', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='WrAc66BaYWKrBFExyBaCCDFBU6mCNkKJ', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid'), ('trialing', 'Trialing')], default='trialing', max_length=20),
        ),
    ]
