# Generated by Django 4.2.11 on 2025-04-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0058_subscription_trial_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='GRpqzv9Qd0zxGswf0tR5K2T9ENG05msj', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='XvcOEqB3BEiRVZbD9MjQjmwekhuh24mG', editable=False, max_length=32, unique=True),
        ),
    ]
