# Generated by Django 4.2.11 on 2025-04-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0059_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='hUxh6sk1TrGb1KzT4T1JBQtEtgLTjRlS', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='cc7lLTh6ynxRRY0lYUtpwKzdIXV6F9A8', editable=False, max_length=32, unique=True),
        ),
    ]
