# Generated by Django 4.2.11 on 2025-04-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0060_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='YzcMuvWYPztyVoYAx9ADl5CROkPPfAWp', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='t0QOYUXxdt8ze19nBFbFAcOYpQE5cK35', editable=False, max_length=32, unique=True),
        ),
    ]
