# Generated by Django 4.2.11 on 2025-04-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0061_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='pKSGdeOvBCvaf8CnLSfZwdn4kD92UY9F', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='w6QCqNMWFOujajuriI2G1phz34tOU15S', editable=False, max_length=32, unique=True),
        ),
    ]
