# Generated by Django 4.2.11 on 2025-04-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0062_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='a9WFGzUPk9IgYaOFxJPff9zStH410QSI', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='C7IZZS9zKLQj2Xk1WKqKOJ490fsd9i4d', editable=False, max_length=32, unique=True),
        ),
    ]
