# Generated by Django 4.2.11 on 2025-04-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0063_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='0JdnqAz0vQ1ROAH4MqwMtTSmfUh4Yxdh', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='HMroMNotREo2HJQhViENEPzI88gimHvX', editable=False, max_length=32, unique=True),
        ),
    ]
