# Generated by Django 4.2.11 on 2025-04-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0063_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='GEQkucJBWHMFe01mV5362spQ3Cx0O0YD', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='0BPWLt9k831k15lVQQRsjnY6Hbw7vyTe', editable=False, max_length=32, unique=True),
        ),
    ]
