# Generated by Django 4.2.11 on 2025-04-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0064_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='7kRBQPRyV2TC18246AKbyRbR1MVkSklU', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='qMDIUo9Y4qOV6aEX1G4GcC0VpowLSGn4', editable=False, max_length=32, unique=True),
        ),
    ]
