# Generated by Django 4.2.11 on 2025-04-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0065_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='U6jc5Y4ShauIL2K2ivY8AQg3EyX0lbAZ', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Mi4MmE15P26A1N5WG74NbwDSxSb0EaNx', editable=False, max_length=32, unique=True),
        ),
    ]
