# Generated by Django 4.2.17 on 2025-08-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0066_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='lUA72ywbs8EVOmT4GVpLkmPKMlMY903r', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='2H4wxXG68YqRnTHHkaPINzimm4FmS7Bh', editable=False, max_length=32, unique=True),
        ),
    ]
