# Generated by Django 4.2.17 on 2025-08-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0067_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='uJJskoGZb4ZtRghnRaikdYHzVX5BIFl2', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Vb4Fq5bmJyhRGwCa3I8DV5EjXyo5s8n2', editable=False, max_length=32, unique=True),
        ),
    ]
