# Generated by Django 4.2.17 on 2025-08-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0068_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='UzJpPUfMGYmOQ0t2WaNvDcSXgDxBgu5g', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='p3QsWYsanYpXeXH7x9TMJN7s63FeTJoZ', editable=False, max_length=32, unique=True),
        ),
    ]
