# Generated by Django 4.2.17 on 2025-08-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0069_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='KFd5p6GmQcnuPHytzvj7SwwE4IE8TsyO', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='PAhD2RckIbNySSlcS9Q3BkBUX8cFZ6wW', editable=False, max_length=32, unique=True),
        ),
    ]
