# Generated by Django 4.2.17 on 2025-08-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0070_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='j6IO5eHs9aIr7MTSD4DDBPVuWO1hMWLo', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='VRTigA6DxcPSejDXugb4M2iRCYoApfQg', editable=False, max_length=32, unique=True),
        ),
    ]
