# Generated by Django 4.2.17 on 2025-08-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0071_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='PtnfEyjpOAO7UFiso1KYVAzHFsTwc1lW', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='VSUOFLCrvrcsz5wQnwk24VtcgILueXDm', editable=False, max_length=32, unique=True),
        ),
    ]
