# Generated by Django 5.2.5 on 2025-08-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0072_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='F0GwMm9qIozc4ndUZe3ufjNOcOPkpDvA', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='pO2ck1m75UdVwSPDgQR0YRRMsDSJRAP2', editable=False, max_length=32, unique=True),
        ),
    ]
