# Generated by Django 5.2.5 on 2025-08-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0073_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='zzxsUyhigykn86iGA3LJrh0NbQZgXNMQ', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='FWyn9JYZvOES0mU2ED5hwMnESpTIZ1XD', editable=False, max_length=32, unique=True),
        ),
    ]
