# Generated by Django 5.2.5 on 2025-09-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0074_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='xGp2bmugPyvsI5q88GvtAuH4hHDaRaCi', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='tUpZK9kohiZN0ppAXPJ0Qxvd6R3HbkSJ', editable=False, max_length=32, unique=True),
        ),
    ]
