# Generated by Django 5.2.5 on 2025-09-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0075_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='VtSicMI6RF8y9hh6aoOxseTflMyWRw0i', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='qBW5Njsq6u4ANvAh4dljZcotVragVJSf', editable=False, max_length=32, unique=True),
        ),
    ]
