# Generated by Django 5.2.5 on 2025-09-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0076_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='3GGoSEBROR3ExnvYLCpxNC8CzXsFdW1Z', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='fDVQnOU0ICiFS70p3ua63Lr9zPDSKZVK', editable=False, max_length=32, unique=True),
        ),
    ]
