# Generated by Django 5.2.5 on 2025-09-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0077_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='eVvl5fBk1EnvPMww1SdBOBpF9UwD9Uiv', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='8UvdHG4RAeLYER4TSqRSfNnBa756glPb', editable=False, max_length=32, unique=True),
        ),
    ]
