# Generated by Django 5.2.5 on 2025-09-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0078_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='M6RDq4EaMHADBiJRr2kQMKnKwjTok6C4', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_category',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('clothing_brand', 'Clothing Brand'), ('spaza', 'Spaza'), ('salon', 'Salon'), ('car_wash', 'Car Wash')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='akhDBqqSKL2YhohsO2RD1s03jAfNWNLD', editable=False, max_length=32, unique=True),
        ),
    ]
