# Generated by Django 5.2.5 on 2025-09-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0079_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='MmqjqKwBeszZKSOZavwTfDCdhJFPE4Tp', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='NdVNnWNAemgdE8bnbOCYxUlk6fOpXMg6', editable=False, max_length=32, unique=True),
        ),
    ]
