# Generated by Django 5.2.5 on 2025-09-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0080_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='PjXJockDpYdC5OyEGxxT7qkvkqifdasm', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='30HSMoF3mluBUHGahTdjL7RviCUVc9Wr', editable=False, max_length=32, unique=True),
        ),
    ]
