# Generated by Django 5.2.5 on 2025-10-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0081_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='v2bXrHtBiBJCgSYienypewngl7Nlk1YO', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Oi2Hm54zLv5DqcM72K1mAMauovUZi3ka', editable=False, max_length=32, unique=True),
        ),
    ]
