# Generated by Django 5.2.7 on 2025-10-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0082_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='XHytiDJP7XdnTjS0dz0tQxwN7UE2mtOV', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='vGJIQT6f0OfAU1cqYwnYF5cWtVu38jAx', editable=False, max_length=32, unique=True),
        ),
    ]
