# Generated by Django 5.2.7 on 2025-10-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0083_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='1pAsDJRS1jHVCy41RbwWFPKMgsYMN3Uf', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='admin_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='AYBjGHK6hlLXwknXN3adhjGAil4TsRnc', editable=False, max_length=32, unique=True),
        ),
    ]
