# Generated by Django 5.2.7 on 2025-10-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0084_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='admin_password',
        ),
        migrations.AddField(
            model_name='customuser',
            name='transaction_pin_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='jz6jZ9uUKGQZekKB3KPsWsBggjmenwRG', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='UmZlyJSe2rDVCgGk7qaprR5YpMheluzH', editable=False, max_length=32, unique=True),
        ),
    ]
