# Generated by Django 5.2.7 on 2025-10-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0085_remove_customuser_admin_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='YXDCLlEGTlKHD1laeITdXjrhqxnqhZSW', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='GvEXWxKG471RZk2e7ags1lfRmhwRiEeL', editable=False, max_length=32, unique=True),
        ),
    ]
