# Generated by Django 5.2.7 on 2025-10-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0086_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='uWAMOEhVKyuvlEVnzWMyaBn4TDvO0w9M', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='7tDBQytx5lRh9LrXbM7OLyhpc0QcxIJm', editable=False, max_length=32, unique=True),
        ),
    ]
