# Generated by Django 5.2.7 on 2025-10-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0087_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='IQrOJeBidUGHUfCIEFVs4FlZVEkT5vbU', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='SPN2KyLrke3G5qSLHcZuv9a4sf32cWb9', editable=False, max_length=32, unique=True),
        ),
    ]
