# Generated by Django 5.2.7 on 2025-10-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0088_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='ffUurMSwHd8yBrpWMJEB0szSXDflLcQ1', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='1ie8BIVBEd8cgDNxqknZw6cWciZW5xUg', editable=False, max_length=32, unique=True),
        ),
    ]
