# Generated by Django 5.2.7 on 2025-10-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0089_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='J6W7CdHzghsuzlor0TWKFGKdrCUYjx6u', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='f6FhZidmGkuyPTJKDjOHzYAKsjIjdfhH', editable=False, max_length=32, unique=True),
        ),
    ]
