# Generated by Django 5.2.7 on 2025-11-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0090_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='kBNWKO7hEOXo7tAp2xbwEik3YcoaBN9G', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='h6TyLrhYQrE7PzsktvRlLmddFZh1AgdT', editable=False, max_length=32, unique=True),
        ),
    ]
